### ISSUE TITLE
Refactor tiny emitter

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-promise-tracker#4]
Current code is too cryptic

**Comment by fjcalzado** [comment]
Hi guys, I was checking  the code of tinyEmitter and I realized that `events` are being registered dynamically as properties of the instance. Something like
```
Instance = {
   'eventNameA' : [fn1, fn2, ...] ,
   'eventNameB' : [fn1, ...] ,
   ...
}
```
In short, this is using a plain object as a map. I was wondering why this is preferred over using a Map (ES6) data structure, or if it is a good/bad practice.

**Comment by fjcalzado** [comment]
As a reference: [Object and Maps compared](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Objects_and_maps_compared)

**Comment by arp82** [comment]
Yeah, tell me about it xD

Personally, I do not like that approach, feels quite obscure (if there are properties around, they should be defined in the class constructor to make things as clear as possible). However, I have kept said approach in my refactoring as I have noticed that every method returned the 'this' object (the instance), and I wanted to keep the current interface as-is. 

As far as this project goes, I feel like we could change it without any problems, but without knowing the reason why it was implemented like that in the first place, I have decided to leave it unchanged for now.

**Comment by arp82** [comment]
Actually, we are not speaking about the same issue exactly, but I agree nonetheless.

Just to make it clearer, instead of using the 'this' object to assign the lists of event subscribers, we could just define a Map property in the constructor (this.allEventSubscribers = new Map() ....) and use this property instead (the way I have refactored the code, this change can be done pretty much straight away)
